### ISSUE TITLE
The Font Style , Font Family & Font Size Cannot be  changed in Captcha Button & Captcha

### ISSUE THREAD

**Issue by forgehustle** [wenlng/go-captcha-react#7]
How To change the Font Style , Font Family & Font Size  in Captcha Button & Captcha title ? 

![Image](https://github.com/user-attachments/assets/5a10c471-a252-4617-8a68-e05a662819c1) only the colour is customizable !!

![Image](https://github.com/user-attachments/assets/363aac79-0799-402d-8269-83ef5d21971d)  the button text font style also not changable 

but on your website below 

![Image](https://github.com/user-attachments/assets/c4edf5b0-2e68-492b-93b3-7c2ac0dd5b70) that font is diffrent  but on my site below its diffrent also i didnt even used that configuration style 

![Image](https://github.com/user-attachments/assets/b27f2ce1-a8e9-4139-a893-b7fc7a1fec54)       my problem below 

![Image](https://github.com/user-attachments/assets/3ff3f0bd-531f-469c-83f6-e985f10050ae)

**Comment by forgehustle** [comment]
brother please respond

**Comment by wenlng** [comment]
Next minor version will include variables for controlling font size and font settings

You can customize styles using overrides, for example:
```css
.go-captcha .gc-button-block, .go-captcha .gc-header {
    font-size: "13px" !important;
    font-family: "Chinese Quotes", "Inter var", "Inter", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Helvetica, Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji" !important;
}
```

The button colors are defined by these three variables:
```css
--go-captcha-theme-btn-color: #ffffff !important;
--go-captcha-theme-btn-bg-color: #ffffff !important;
--go-captcha-theme-btn-border-color: #ffffff !important;
```
